#!/bin/bash
#Made by tin3w5
TASK=$1
KILLER=$?
STATUS=`/usr/sbin/7con 1 $TASK`
if [ "$STATUS" == '0' ]; then
    echo "The Control not in the List!!!"
    exit 127
fi
pkill -9 `/usr/sbin/7con 0 $TASK `
if [ $KILLER -eq 0 ]; then
    echo '###################################'
    echo ' ###################################'
    echo "  ### Stoped,starting the task... ###"
    echo ' ###################################'
    echo '###################################'
else
    echo '   ######################################'
    echo '  ######################################'
    echo " #### Stop failed or unknow error. ####"
    echo '  ######################################'
    echo '   ######################################'
    tail -15 /var/log/messages
fi
